SET C51INC=D:\Program Files\keil\C51\Inc;D:\Program Files\keil\C51\Inc\Atmel
SET C51LIB=D:\Program Files\keil\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\CONVER~1.__I
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\delay.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\font5_7.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\FONT8_8.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\FONT24~1.__I
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\GUI_BA~1.__I
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\GUI_ST~1.__I
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\lcmdrv.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\loadbit.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\main.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\menu.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\spline.__i
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\output\windows.__i
"D:\Program Files\keil\C51\BIN\BL51.EXE" @.\output\GUI.lnp
"D:\Program Files\keil\C51\BIN\OH51.EXE" ".\output\GUI" 
